[package]
name = "nucleo_nvim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nucleo-matcher = "0.3.1"
mlua = { version = "0.9.7", features = ["luajit", "module"] }
